name: Android Release Build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 1

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Accept licenses
      run: yes | sdkmanager --licenses

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build release
      run: ./gradlew assembleRelease

    - name: Decode keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore.jks

    - name: Sign the APK
      run: |
        apksigner sign \
          --ks keystore.jks \
          --ks-key-alias "${{ secrets.KEY_ALIAS }}" \
          --ks-pass pass:"${{ secrets.KEYSTORE_PASSWORD }}" \
          --key-pass pass:"${{ secrets.KEY_PASSWORD }}" \
          ui/build/outputs/apk/release/ui-release-unsigned.apk

    - name: Upload APK to GitHub Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ui/build/outputs/apk/release/ui-release-unsigned.apk
        asset_name: app-release.apk
        tag: ${{ github.ref_name }}
        overwrite: true
